---
# For installing docker-compose, please refer page
# https://docs.docker.com/compose/install/
# For using docker compose
# 1. start docker container, like vagrant, go under folder
#    contains docker-compose.yml file and run:
#    $ docker-compose up -d
# 2. stop the container
#    $ docker-compose stop
# 3. remove the container
#    $ docker-compose rm -f


dev:
  container_name: imagetest
  image: plotly/testbed:latest
  volumes: 
    - .:/var/www/streambed/image_server/plotly.js
  ports:
    - "9010:9010"
    - "2022:22"
