name: ğŸ€ Spellchecker

on: [pull_request]

jobs:
  misspell:
    name: ğŸ§¹ Check Spelling
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ¥­ Check Out
        uses: actions/checkout@v2
      - name: ğŸ—ï¸ Install
        run: |
          wget -O - -q https://git.io/misspell | sh -s -- -b .
      - name: ğŸ§¹ Misspell
        run: |
          find . -not -path './build**'  -not -path './dist**' -not -path './node_modules**' -type f | xargs misspell -error -i 'transforme,verificato'
